blank_issues_enabled: true
contact_links:
  - name: 💬 Community Discussion
    url: https://github.com/bywhitebird/community/discussions
    about: Ask questions and discuss ideas with the community.
