name: 🚀 New Feature
description: Create an issue to track the development of a new feature.
title: "<Feature name>"
labels: [enhancement]

body:
  - type: input
    id: description
    attributes:
      label: Description
      description: Describe the new feature you are planning to add to the project.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the criteria that must be met in order for this feature to be considered complete.
      placeholder: |
        - Criteria 1
        - Criteria 2
        - Criteria 3
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: List the tasks that must be completed in order to implement this feature.
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Include any other relevant information about the new feature, such as related issues or potential challenges.
      placeholder: |
        Include any other relevant information about the new feature, such as related issues or potential challenges.
